spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/micro-task
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

server:
  port: 8083

keycloak:
  realm: cydeo-dev
  auth-server-url: http://localhost:8080/auth
  ssl-required: none
  resource: ticketing-app
  credentials:
    secret: kL61LtbhRQ4i8wKM6M0QDHpYEF7utx3K
  use-resource-role-mappings: true
  bearer-only: true

master:
  user:
    username: admin
    password: admin
  realm: master
  client: master-client
