spring.application.name=discovery-service
server.port=8761
eureka.instance.hostname=localhost'
eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false


#spring:
#  application:
#    name: discovery-service
#
#server:
#  port: 8761
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http//localhost:${server.port}/eureka/
#    register-with-eureka: false
#    fetch-registry: false

#eureka.instance.hostname=localhost'
#eureka.client.fetch-registry=false
#eureka.client.register-with-eureka=false